<?php

namespace AppBundle\Repository;

/**
 * AgendatypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendatypeRepository extends \Doctrine\ORM\EntityRepository
{
}
