<?php

namespace AppBundle\Repository;

/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerRepository extends \Doctrine\ORM\EntityRepository
{
	public function notDeleted( )
    {
		$queryBuilder  = $this->createQueryBuilder('o');
		$queryBuilder->where("o.name <> 'Supprimé'");
		$queryBuilder->orderBy('o.id', 'ASC');
		return $queryBuilder ->getQuery()->getArrayResult();
	}
}
