<?php

namespace AppBundle\Repository;

/**
 * PhonetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhonetypeRepository extends \Doctrine\ORM\EntityRepository
{
}
