<?php

namespace AppBundle\Repository;

/**
 * TagendaLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagendaLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
