<?php

namespace AppBundle\Repository;

/**
 * TcalltypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TcalltypeRepository extends \Doctrine\ORM\EntityRepository
{
}
