<?php

namespace AppBundle\Repository;

/**
 * TclientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TclientRepository extends \Doctrine\ORM\EntityRepository
{
}
