<?php

namespace AppBundle\Repository;

/**
 * TphoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TphoneRepository extends \Doctrine\ORM\EntityRepository
{
}
